###
### Author: ngoanh2n
### https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide
###
version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "03:00"
      timezone: Asia/Ho_Chi_Minh
    target-branch: develop
    rebase-strategy: disabled
    open-pull-requests-limit: 15
