version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Asia/Ho_Chi_Minh
    assignees:
      - ngoanh2n
    target-branch: master
    rebase-strategy: disabled
