###
### Author: ngoanh2n
### https://docs.github.com/en/actions
### https://github.com/marketplace?type=actions
###
name: Build
on:
  pull_request:
    types: [opened, review_requested]
jobs:
  test:
    defaults:
      run:
        shell: bash
    name: ubuntu-latest_java17
    runs-on: ubuntu-latest
    steps:
      - name: "[Prepare] Checkout"
        uses: actions/checkout@v4
      - name: "[Prepare] Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: "[Build] Execute"
        run: ./gradlew clean build
      - if: success() || failure()
        name: "[Report] JUnit report"
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: JUnit ubuntu-latest_java17
          report_paths: build/reports/test/TEST-*.xml
